<?php
/**
 * DocumentTypeEnum
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Monite Partner API
 *
 * The Monite REST API, for Monite partners to integrate with our solution.
 *
 * The version of the OpenAPI document: 2023-03-14
 * Contact: developers@monite.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * DocumentTypeEnum Class Doc Comment
 *
 * @category Class
 * @description An enumeration.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DocumentTypeEnum
{
    /**
     * Possible values of this enum
     */
    public const QUOTE = 'quote';

    public const INVOICE = 'invoice';

    public const CREDIT_NOTE = 'credit_note';

    public const DISCOUNT_REMINDER = 'discount_reminder';

    public const FINAL_REMINDER = 'final_reminder';

    public const PAYABLES_PURCHASE_ORDER = 'payables_purchase_order';

    public const OVERDUE_REMINDER = 'overdue_reminder';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::QUOTE,
            self::INVOICE,
            self::CREDIT_NOTE,
            self::DISCOUNT_REMINDER,
            self::FINAL_REMINDER,
            self::PAYABLES_PURCHASE_ORDER,
            self::OVERDUE_REMINDER
        ];
    }
}


