<?php
/**
 * PayableResponseSchema
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Monite Partner API
 *
 * The Monite REST API, for Monite partners to integrate with our solution.
 *
 * The version of the OpenAPI document: 2023-03-14
 * Contact: developers@monite.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * PayableResponseSchema Class Doc Comment
 *
 * @category Class
 * @description Represents an Accounts Payable document received from a vendor or supplier.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PayableResponseSchema implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PayableResponseSchema';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'entity_id' => 'string',
        'marked_as_paid_with_comment' => 'string',
        'marked_as_paid_by_entity_user_id' => 'string',
        'status' => '\OpenAPI\Client\Model\PayableStateEnum',
        'source_of_payable_data' => '\OpenAPI\Client\Model\SourceOfPayableDataEnum',
        'currency' => '\OpenAPI\Client\Model\CurrencyEnum',
        'amount' => 'int',
        'description' => 'string',
        'due_date' => '\DateTime',
        'payment_terms' => '\OpenAPI\Client\Model\PayableResponseSchemaPaymentTerms',
        'suggested_payment_term' => '\OpenAPI\Client\Model\PayableResponseSchemaSuggestedPaymentTerm',
        'issued_at' => '\DateTime',
        'counterpart_bank_id' => 'string',
        'counterpart_id' => 'string',
        'counterpart_account_id' => 'string',
        'counterpart_name' => 'string',
        'counterpart_tax_id' => 'string',
        'counterpart_address' => '\OpenAPI\Client\Model\PayableResponseSchemaCounterpartAddress',
        'payable_origin' => '\OpenAPI\Client\Model\PayableOriginEnum',
        'was_created_by_user_id' => 'string',
        'was_created_by_external_user_name' => 'string',
        'was_created_by_external_user_id' => 'string',
        'currency_exchange' => '\OpenAPI\Client\Model\CurrencyExchangeSchema',
        'file' => '\OpenAPI\Client\Model\PayableResponseSchemaFile',
        'tags' => '\OpenAPI\Client\Model\TagReadSchema[]',
        'created_at' => '\DateTime',
        'updated_at' => '\DateTime',
        'other_extracted_data' => '\OpenAPI\Client\Model\PayableResponseSchemaOtherExtractedData',
        'applied_policy' => 'string',
        'document_id' => 'string',
        'subtotal' => 'int',
        'tax' => 'int',
        'sender' => 'string',
        'line_items' => '\OpenAPI\Client\Model\LineItemDataResponse[]',
        'ocr_request_id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'uuid',
        'entity_id' => 'uuid',
        'marked_as_paid_with_comment' => null,
        'marked_as_paid_by_entity_user_id' => 'uuid',
        'status' => null,
        'source_of_payable_data' => null,
        'currency' => null,
        'amount' => null,
        'description' => null,
        'due_date' => 'date',
        'payment_terms' => null,
        'suggested_payment_term' => null,
        'issued_at' => 'date',
        'counterpart_bank_id' => null,
        'counterpart_id' => 'uuid',
        'counterpart_account_id' => null,
        'counterpart_name' => null,
        'counterpart_tax_id' => null,
        'counterpart_address' => null,
        'payable_origin' => null,
        'was_created_by_user_id' => 'uuid',
        'was_created_by_external_user_name' => null,
        'was_created_by_external_user_id' => null,
        'currency_exchange' => null,
        'file' => null,
        'tags' => null,
        'created_at' => 'date-time',
        'updated_at' => 'date-time',
        'other_extracted_data' => null,
        'applied_policy' => null,
        'document_id' => null,
        'subtotal' => null,
        'tax' => null,
        'sender' => 'email',
        'line_items' => null,
        'ocr_request_id' => 'uuid'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
		'entity_id' => false,
		'marked_as_paid_with_comment' => false,
		'marked_as_paid_by_entity_user_id' => false,
		'status' => false,
		'source_of_payable_data' => false,
		'currency' => false,
		'amount' => false,
		'description' => false,
		'due_date' => false,
		'payment_terms' => false,
		'suggested_payment_term' => false,
		'issued_at' => false,
		'counterpart_bank_id' => false,
		'counterpart_id' => false,
		'counterpart_account_id' => false,
		'counterpart_name' => false,
		'counterpart_tax_id' => false,
		'counterpart_address' => false,
		'payable_origin' => false,
		'was_created_by_user_id' => false,
		'was_created_by_external_user_name' => false,
		'was_created_by_external_user_id' => false,
		'currency_exchange' => false,
		'file' => false,
		'tags' => false,
		'created_at' => false,
		'updated_at' => false,
		'other_extracted_data' => false,
		'applied_policy' => false,
		'document_id' => false,
		'subtotal' => false,
		'tax' => false,
		'sender' => false,
		'line_items' => false,
		'ocr_request_id' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'entity_id' => 'entity_id',
        'marked_as_paid_with_comment' => 'marked_as_paid_with_comment',
        'marked_as_paid_by_entity_user_id' => 'marked_as_paid_by_entity_user_id',
        'status' => 'status',
        'source_of_payable_data' => 'source_of_payable_data',
        'currency' => 'currency',
        'amount' => 'amount',
        'description' => 'description',
        'due_date' => 'due_date',
        'payment_terms' => 'payment_terms',
        'suggested_payment_term' => 'suggested_payment_term',
        'issued_at' => 'issued_at',
        'counterpart_bank_id' => 'counterpart_bank_id',
        'counterpart_id' => 'counterpart_id',
        'counterpart_account_id' => 'counterpart_account_id',
        'counterpart_name' => 'counterpart_name',
        'counterpart_tax_id' => 'counterpart_tax_id',
        'counterpart_address' => 'counterpart_address',
        'payable_origin' => 'payable_origin',
        'was_created_by_user_id' => 'was_created_by_user_id',
        'was_created_by_external_user_name' => 'was_created_by_external_user_name',
        'was_created_by_external_user_id' => 'was_created_by_external_user_id',
        'currency_exchange' => 'currency_exchange',
        'file' => 'file',
        'tags' => 'tags',
        'created_at' => 'created_at',
        'updated_at' => 'updated_at',
        'other_extracted_data' => 'other_extracted_data',
        'applied_policy' => 'applied_policy',
        'document_id' => 'document_id',
        'subtotal' => 'subtotal',
        'tax' => 'tax',
        'sender' => 'sender',
        'line_items' => 'line_items',
        'ocr_request_id' => 'ocr_request_id'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'entity_id' => 'setEntityId',
        'marked_as_paid_with_comment' => 'setMarkedAsPaidWithComment',
        'marked_as_paid_by_entity_user_id' => 'setMarkedAsPaidByEntityUserId',
        'status' => 'setStatus',
        'source_of_payable_data' => 'setSourceOfPayableData',
        'currency' => 'setCurrency',
        'amount' => 'setAmount',
        'description' => 'setDescription',
        'due_date' => 'setDueDate',
        'payment_terms' => 'setPaymentTerms',
        'suggested_payment_term' => 'setSuggestedPaymentTerm',
        'issued_at' => 'setIssuedAt',
        'counterpart_bank_id' => 'setCounterpartBankId',
        'counterpart_id' => 'setCounterpartId',
        'counterpart_account_id' => 'setCounterpartAccountId',
        'counterpart_name' => 'setCounterpartName',
        'counterpart_tax_id' => 'setCounterpartTaxId',
        'counterpart_address' => 'setCounterpartAddress',
        'payable_origin' => 'setPayableOrigin',
        'was_created_by_user_id' => 'setWasCreatedByUserId',
        'was_created_by_external_user_name' => 'setWasCreatedByExternalUserName',
        'was_created_by_external_user_id' => 'setWasCreatedByExternalUserId',
        'currency_exchange' => 'setCurrencyExchange',
        'file' => 'setFile',
        'tags' => 'setTags',
        'created_at' => 'setCreatedAt',
        'updated_at' => 'setUpdatedAt',
        'other_extracted_data' => 'setOtherExtractedData',
        'applied_policy' => 'setAppliedPolicy',
        'document_id' => 'setDocumentId',
        'subtotal' => 'setSubtotal',
        'tax' => 'setTax',
        'sender' => 'setSender',
        'line_items' => 'setLineItems',
        'ocr_request_id' => 'setOcrRequestId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'entity_id' => 'getEntityId',
        'marked_as_paid_with_comment' => 'getMarkedAsPaidWithComment',
        'marked_as_paid_by_entity_user_id' => 'getMarkedAsPaidByEntityUserId',
        'status' => 'getStatus',
        'source_of_payable_data' => 'getSourceOfPayableData',
        'currency' => 'getCurrency',
        'amount' => 'getAmount',
        'description' => 'getDescription',
        'due_date' => 'getDueDate',
        'payment_terms' => 'getPaymentTerms',
        'suggested_payment_term' => 'getSuggestedPaymentTerm',
        'issued_at' => 'getIssuedAt',
        'counterpart_bank_id' => 'getCounterpartBankId',
        'counterpart_id' => 'getCounterpartId',
        'counterpart_account_id' => 'getCounterpartAccountId',
        'counterpart_name' => 'getCounterpartName',
        'counterpart_tax_id' => 'getCounterpartTaxId',
        'counterpart_address' => 'getCounterpartAddress',
        'payable_origin' => 'getPayableOrigin',
        'was_created_by_user_id' => 'getWasCreatedByUserId',
        'was_created_by_external_user_name' => 'getWasCreatedByExternalUserName',
        'was_created_by_external_user_id' => 'getWasCreatedByExternalUserId',
        'currency_exchange' => 'getCurrencyExchange',
        'file' => 'getFile',
        'tags' => 'getTags',
        'created_at' => 'getCreatedAt',
        'updated_at' => 'getUpdatedAt',
        'other_extracted_data' => 'getOtherExtractedData',
        'applied_policy' => 'getAppliedPolicy',
        'document_id' => 'getDocumentId',
        'subtotal' => 'getSubtotal',
        'tax' => 'getTax',
        'sender' => 'getSender',
        'line_items' => 'getLineItems',
        'ocr_request_id' => 'getOcrRequestId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('entity_id', $data ?? [], null);
        $this->setIfExists('marked_as_paid_with_comment', $data ?? [], null);
        $this->setIfExists('marked_as_paid_by_entity_user_id', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('source_of_payable_data', $data ?? [], null);
        $this->setIfExists('currency', $data ?? [], null);
        $this->setIfExists('amount', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('due_date', $data ?? [], null);
        $this->setIfExists('payment_terms', $data ?? [], null);
        $this->setIfExists('suggested_payment_term', $data ?? [], null);
        $this->setIfExists('issued_at', $data ?? [], null);
        $this->setIfExists('counterpart_bank_id', $data ?? [], null);
        $this->setIfExists('counterpart_id', $data ?? [], null);
        $this->setIfExists('counterpart_account_id', $data ?? [], null);
        $this->setIfExists('counterpart_name', $data ?? [], null);
        $this->setIfExists('counterpart_tax_id', $data ?? [], null);
        $this->setIfExists('counterpart_address', $data ?? [], null);
        $this->setIfExists('payable_origin', $data ?? [], null);
        $this->setIfExists('was_created_by_user_id', $data ?? [], null);
        $this->setIfExists('was_created_by_external_user_name', $data ?? [], null);
        $this->setIfExists('was_created_by_external_user_id', $data ?? [], null);
        $this->setIfExists('currency_exchange', $data ?? [], null);
        $this->setIfExists('file', $data ?? [], null);
        $this->setIfExists('tags', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('updated_at', $data ?? [], null);
        $this->setIfExists('other_extracted_data', $data ?? [], null);
        $this->setIfExists('applied_policy', $data ?? [], null);
        $this->setIfExists('document_id', $data ?? [], null);
        $this->setIfExists('subtotal', $data ?? [], null);
        $this->setIfExists('tax', $data ?? [], null);
        $this->setIfExists('sender', $data ?? [], null);
        $this->setIfExists('line_items', $data ?? [], null);
        $this->setIfExists('ocr_request_id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['entity_id'] === null) {
            $invalidProperties[] = "'entity_id' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['source_of_payable_data'] === null) {
            $invalidProperties[] = "'source_of_payable_data' can't be null";
        }
        if ($this->container['payable_origin'] === null) {
            $invalidProperties[] = "'payable_origin' can't be null";
        }
        if ($this->container['created_at'] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        if ($this->container['updated_at'] === null) {
            $invalidProperties[] = "'updated_at' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id A unique ID assigned to this payable.
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets entity_id
     *
     * @return string
     */
    public function getEntityId()
    {
        return $this->container['entity_id'];
    }

    /**
     * Sets entity_id
     *
     * @param string $entity_id The ID of the entity to which the payable was issued.
     *
     * @return self
     */
    public function setEntityId($entity_id)
    {
        if (is_null($entity_id)) {
            throw new \InvalidArgumentException('non-nullable entity_id cannot be null');
        }
        $this->container['entity_id'] = $entity_id;

        return $this;
    }

    /**
     * Gets marked_as_paid_with_comment
     *
     * @return string|null
     */
    public function getMarkedAsPaidWithComment()
    {
        return $this->container['marked_as_paid_with_comment'];
    }

    /**
     * Sets marked_as_paid_with_comment
     *
     * @param string|null $marked_as_paid_with_comment An arbitrary comment that describes how and when this payable was paid.
     *
     * @return self
     */
    public function setMarkedAsPaidWithComment($marked_as_paid_with_comment)
    {
        if (is_null($marked_as_paid_with_comment)) {
            throw new \InvalidArgumentException('non-nullable marked_as_paid_with_comment cannot be null');
        }
        $this->container['marked_as_paid_with_comment'] = $marked_as_paid_with_comment;

        return $this;
    }

    /**
     * Gets marked_as_paid_by_entity_user_id
     *
     * @return string|null
     */
    public function getMarkedAsPaidByEntityUserId()
    {
        return $this->container['marked_as_paid_by_entity_user_id'];
    }

    /**
     * Sets marked_as_paid_by_entity_user_id
     *
     * @param string|null $marked_as_paid_by_entity_user_id The ID of the entity user who marked this document as paid.
     *
     * @return self
     */
    public function setMarkedAsPaidByEntityUserId($marked_as_paid_by_entity_user_id)
    {
        if (is_null($marked_as_paid_by_entity_user_id)) {
            throw new \InvalidArgumentException('non-nullable marked_as_paid_by_entity_user_id cannot be null');
        }
        $this->container['marked_as_paid_by_entity_user_id'] = $marked_as_paid_by_entity_user_id;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \OpenAPI\Client\Model\PayableStateEnum
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \OpenAPI\Client\Model\PayableStateEnum $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets source_of_payable_data
     *
     * @return \OpenAPI\Client\Model\SourceOfPayableDataEnum
     */
    public function getSourceOfPayableData()
    {
        return $this->container['source_of_payable_data'];
    }

    /**
     * Sets source_of_payable_data
     *
     * @param \OpenAPI\Client\Model\SourceOfPayableDataEnum $source_of_payable_data source_of_payable_data
     *
     * @return self
     */
    public function setSourceOfPayableData($source_of_payable_data)
    {
        if (is_null($source_of_payable_data)) {
            throw new \InvalidArgumentException('non-nullable source_of_payable_data cannot be null');
        }
        $this->container['source_of_payable_data'] = $source_of_payable_data;

        return $this;
    }

    /**
     * Gets currency
     *
     * @return \OpenAPI\Client\Model\CurrencyEnum|null
     */
    public function getCurrency()
    {
        return $this->container['currency'];
    }

    /**
     * Sets currency
     *
     * @param \OpenAPI\Client\Model\CurrencyEnum|null $currency currency
     *
     * @return self
     */
    public function setCurrency($currency)
    {
        if (is_null($currency)) {
            throw new \InvalidArgumentException('non-nullable currency cannot be null');
        }
        $this->container['currency'] = $currency;

        return $this;
    }

    /**
     * Gets amount
     *
     * @return int|null
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param int|null $amount The total amount to be paid, in [minor units](https://docs.monite.com/docs/currencies#minor-units). For example, $12.50 is represented as 1250.
     *
     * @return self
     */
    public function setAmount($amount)
    {
        if (is_null($amount)) {
            throw new \InvalidArgumentException('non-nullable amount cannot be null');
        }
        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description An arbitrary description of this payable.
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets due_date
     *
     * @return \DateTime|null
     */
    public function getDueDate()
    {
        return $this->container['due_date'];
    }

    /**
     * Sets due_date
     *
     * @param \DateTime|null $due_date The date by which the payable must be paid, in the YYYY-MM-DD format. If the payable specifies payment terms with early payment discounts, this is the final payment date.
     *
     * @return self
     */
    public function setDueDate($due_date)
    {
        if (is_null($due_date)) {
            throw new \InvalidArgumentException('non-nullable due_date cannot be null');
        }
        $this->container['due_date'] = $due_date;

        return $this;
    }

    /**
     * Gets payment_terms
     *
     * @return \OpenAPI\Client\Model\PayableResponseSchemaPaymentTerms|null
     */
    public function getPaymentTerms()
    {
        return $this->container['payment_terms'];
    }

    /**
     * Sets payment_terms
     *
     * @param \OpenAPI\Client\Model\PayableResponseSchemaPaymentTerms|null $payment_terms payment_terms
     *
     * @return self
     */
    public function setPaymentTerms($payment_terms)
    {
        if (is_null($payment_terms)) {
            throw new \InvalidArgumentException('non-nullable payment_terms cannot be null');
        }
        $this->container['payment_terms'] = $payment_terms;

        return $this;
    }

    /**
     * Gets suggested_payment_term
     *
     * @return \OpenAPI\Client\Model\PayableResponseSchemaSuggestedPaymentTerm|null
     */
    public function getSuggestedPaymentTerm()
    {
        return $this->container['suggested_payment_term'];
    }

    /**
     * Sets suggested_payment_term
     *
     * @param \OpenAPI\Client\Model\PayableResponseSchemaSuggestedPaymentTerm|null $suggested_payment_term suggested_payment_term
     *
     * @return self
     */
    public function setSuggestedPaymentTerm($suggested_payment_term)
    {
        if (is_null($suggested_payment_term)) {
            throw new \InvalidArgumentException('non-nullable suggested_payment_term cannot be null');
        }
        $this->container['suggested_payment_term'] = $suggested_payment_term;

        return $this;
    }

    /**
     * Gets issued_at
     *
     * @return \DateTime|null
     */
    public function getIssuedAt()
    {
        return $this->container['issued_at'];
    }

    /**
     * Sets issued_at
     *
     * @param \DateTime|null $issued_at The date when the payable was issued, in the YYYY-MM-DD format.
     *
     * @return self
     */
    public function setIssuedAt($issued_at)
    {
        if (is_null($issued_at)) {
            throw new \InvalidArgumentException('non-nullable issued_at cannot be null');
        }
        $this->container['issued_at'] = $issued_at;

        return $this;
    }

    /**
     * Gets counterpart_bank_id
     *
     * @return string|null
     */
    public function getCounterpartBankId()
    {
        return $this->container['counterpart_bank_id'];
    }

    /**
     * Sets counterpart_bank_id
     *
     * @param string|null $counterpart_bank_id SWIFT code (BIC) of the vendor's bank (if specified in the payable document).
     *
     * @return self
     */
    public function setCounterpartBankId($counterpart_bank_id)
    {
        if (is_null($counterpart_bank_id)) {
            throw new \InvalidArgumentException('non-nullable counterpart_bank_id cannot be null');
        }
        $this->container['counterpart_bank_id'] = $counterpart_bank_id;

        return $this;
    }

    /**
     * Gets counterpart_id
     *
     * @return string|null
     */
    public function getCounterpartId()
    {
        return $this->container['counterpart_id'];
    }

    /**
     * Sets counterpart_id
     *
     * @param string|null $counterpart_id The ID of the counterpart object that represents the vendor or supplier.
     *
     * @return self
     */
    public function setCounterpartId($counterpart_id)
    {
        if (is_null($counterpart_id)) {
            throw new \InvalidArgumentException('non-nullable counterpart_id cannot be null');
        }
        $this->container['counterpart_id'] = $counterpart_id;

        return $this;
    }

    /**
     * Gets counterpart_account_id
     *
     * @return string|null
     */
    public function getCounterpartAccountId()
    {
        return $this->container['counterpart_account_id'];
    }

    /**
     * Sets counterpart_account_id
     *
     * @param string|null $counterpart_account_id Vendor's bank account number, IBAN, or similar (if specified in the payable document).
     *
     * @return self
     */
    public function setCounterpartAccountId($counterpart_account_id)
    {
        if (is_null($counterpart_account_id)) {
            throw new \InvalidArgumentException('non-nullable counterpart_account_id cannot be null');
        }
        $this->container['counterpart_account_id'] = $counterpart_account_id;

        return $this;
    }

    /**
     * Gets counterpart_name
     *
     * @return string|null
     */
    public function getCounterpartName()
    {
        return $this->container['counterpart_name'];
    }

    /**
     * Sets counterpart_name
     *
     * @param string|null $counterpart_name Vendor or supplier name.
     *
     * @return self
     */
    public function setCounterpartName($counterpart_name)
    {
        if (is_null($counterpart_name)) {
            throw new \InvalidArgumentException('non-nullable counterpart_name cannot be null');
        }
        $this->container['counterpart_name'] = $counterpart_name;

        return $this;
    }

    /**
     * Gets counterpart_tax_id
     *
     * @return string|null
     */
    public function getCounterpartTaxId()
    {
        return $this->container['counterpart_tax_id'];
    }

    /**
     * Sets counterpart_tax_id
     *
     * @param string|null $counterpart_tax_id The tax id of the counterpart.
     *
     * @return self
     */
    public function setCounterpartTaxId($counterpart_tax_id)
    {
        if (is_null($counterpart_tax_id)) {
            throw new \InvalidArgumentException('non-nullable counterpart_tax_id cannot be null');
        }
        $this->container['counterpart_tax_id'] = $counterpart_tax_id;

        return $this;
    }

    /**
     * Gets counterpart_address
     *
     * @return \OpenAPI\Client\Model\PayableResponseSchemaCounterpartAddress|null
     */
    public function getCounterpartAddress()
    {
        return $this->container['counterpart_address'];
    }

    /**
     * Sets counterpart_address
     *
     * @param \OpenAPI\Client\Model\PayableResponseSchemaCounterpartAddress|null $counterpart_address counterpart_address
     *
     * @return self
     */
    public function setCounterpartAddress($counterpart_address)
    {
        if (is_null($counterpart_address)) {
            throw new \InvalidArgumentException('non-nullable counterpart_address cannot be null');
        }
        $this->container['counterpart_address'] = $counterpart_address;

        return $this;
    }

    /**
     * Gets payable_origin
     *
     * @return \OpenAPI\Client\Model\PayableOriginEnum
     */
    public function getPayableOrigin()
    {
        return $this->container['payable_origin'];
    }

    /**
     * Sets payable_origin
     *
     * @param \OpenAPI\Client\Model\PayableOriginEnum $payable_origin payable_origin
     *
     * @return self
     */
    public function setPayableOrigin($payable_origin)
    {
        if (is_null($payable_origin)) {
            throw new \InvalidArgumentException('non-nullable payable_origin cannot be null');
        }
        $this->container['payable_origin'] = $payable_origin;

        return $this;
    }

    /**
     * Gets was_created_by_user_id
     *
     * @return string|null
     */
    public function getWasCreatedByUserId()
    {
        return $this->container['was_created_by_user_id'];
    }

    /**
     * Sets was_created_by_user_id
     *
     * @param string|null $was_created_by_user_id was_created_by_user_id
     *
     * @return self
     */
    public function setWasCreatedByUserId($was_created_by_user_id)
    {
        if (is_null($was_created_by_user_id)) {
            throw new \InvalidArgumentException('non-nullable was_created_by_user_id cannot be null');
        }
        $this->container['was_created_by_user_id'] = $was_created_by_user_id;

        return $this;
    }

    /**
     * Gets was_created_by_external_user_name
     *
     * @return string|null
     */
    public function getWasCreatedByExternalUserName()
    {
        return $this->container['was_created_by_external_user_name'];
    }

    /**
     * Sets was_created_by_external_user_name
     *
     * @param string|null $was_created_by_external_user_name was_created_by_external_user_name
     *
     * @return self
     */
    public function setWasCreatedByExternalUserName($was_created_by_external_user_name)
    {
        if (is_null($was_created_by_external_user_name)) {
            throw new \InvalidArgumentException('non-nullable was_created_by_external_user_name cannot be null');
        }
        $this->container['was_created_by_external_user_name'] = $was_created_by_external_user_name;

        return $this;
    }

    /**
     * Gets was_created_by_external_user_id
     *
     * @return string|null
     */
    public function getWasCreatedByExternalUserId()
    {
        return $this->container['was_created_by_external_user_id'];
    }

    /**
     * Sets was_created_by_external_user_id
     *
     * @param string|null $was_created_by_external_user_id was_created_by_external_user_id
     *
     * @return self
     */
    public function setWasCreatedByExternalUserId($was_created_by_external_user_id)
    {
        if (is_null($was_created_by_external_user_id)) {
            throw new \InvalidArgumentException('non-nullable was_created_by_external_user_id cannot be null');
        }
        $this->container['was_created_by_external_user_id'] = $was_created_by_external_user_id;

        return $this;
    }

    /**
     * Gets currency_exchange
     *
     * @return \OpenAPI\Client\Model\CurrencyExchangeSchema|null
     */
    public function getCurrencyExchange()
    {
        return $this->container['currency_exchange'];
    }

    /**
     * Sets currency_exchange
     *
     * @param \OpenAPI\Client\Model\CurrencyExchangeSchema|null $currency_exchange currency_exchange
     *
     * @return self
     */
    public function setCurrencyExchange($currency_exchange)
    {
        if (is_null($currency_exchange)) {
            throw new \InvalidArgumentException('non-nullable currency_exchange cannot be null');
        }
        $this->container['currency_exchange'] = $currency_exchange;

        return $this;
    }

    /**
     * Gets file
     *
     * @return \OpenAPI\Client\Model\PayableResponseSchemaFile|null
     */
    public function getFile()
    {
        return $this->container['file'];
    }

    /**
     * Sets file
     *
     * @param \OpenAPI\Client\Model\PayableResponseSchemaFile|null $file file
     *
     * @return self
     */
    public function setFile($file)
    {
        if (is_null($file)) {
            throw new \InvalidArgumentException('non-nullable file cannot be null');
        }
        $this->container['file'] = $file;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return \OpenAPI\Client\Model\TagReadSchema[]|null
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param \OpenAPI\Client\Model\TagReadSchema[]|null $tags A list of user-defined tags (labels) assigned to this payable. Tags can be used to trigger a specific approval policy for this payable.
     *
     * @return self
     */
    public function setTags($tags)
    {
        if (is_null($tags)) {
            throw new \InvalidArgumentException('non-nullable tags cannot be null');
        }
        $this->container['tags'] = $tags;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime $created_at UTC date and time when this payable was created. Timestamps follow the [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime $updated_at UTC date and time when this payable was last updated. Timestamps follow the [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        if (is_null($updated_at)) {
            throw new \InvalidArgumentException('non-nullable updated_at cannot be null');
        }
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Gets other_extracted_data
     *
     * @return \OpenAPI\Client\Model\PayableResponseSchemaOtherExtractedData|null
     */
    public function getOtherExtractedData()
    {
        return $this->container['other_extracted_data'];
    }

    /**
     * Sets other_extracted_data
     *
     * @param \OpenAPI\Client\Model\PayableResponseSchemaOtherExtractedData|null $other_extracted_data other_extracted_data
     *
     * @return self
     */
    public function setOtherExtractedData($other_extracted_data)
    {
        if (is_null($other_extracted_data)) {
            throw new \InvalidArgumentException('non-nullable other_extracted_data cannot be null');
        }
        $this->container['other_extracted_data'] = $other_extracted_data;

        return $this;
    }

    /**
     * Gets applied_policy
     *
     * @return string|null
     */
    public function getAppliedPolicy()
    {
        return $this->container['applied_policy'];
    }

    /**
     * Sets applied_policy
     *
     * @param string|null $applied_policy The name of an existing workflow (approval policy) that applies to this payable, if any. A workflow is applied if the payable matches the workflow trigger conditions.
     *
     * @return self
     */
    public function setAppliedPolicy($applied_policy)
    {
        if (is_null($applied_policy)) {
            throw new \InvalidArgumentException('non-nullable applied_policy cannot be null');
        }
        $this->container['applied_policy'] = $applied_policy;

        return $this;
    }

    /**
     * Gets document_id
     *
     * @return string|null
     */
    public function getDocumentId()
    {
        return $this->container['document_id'];
    }

    /**
     * Sets document_id
     *
     * @param string|null $document_id A unique invoice number assigned by the invoice issuer for payment tracking purposes. This is different from `id` which is an internal ID created automatically by Monite.
     *
     * @return self
     */
    public function setDocumentId($document_id)
    {
        if (is_null($document_id)) {
            throw new \InvalidArgumentException('non-nullable document_id cannot be null');
        }
        $this->container['document_id'] = $document_id;

        return $this;
    }

    /**
     * Gets subtotal
     *
     * @return int|null
     */
    public function getSubtotal()
    {
        return $this->container['subtotal'];
    }

    /**
     * Sets subtotal
     *
     * @param int|null $subtotal The subtotal amount to be paid, in [minor units](https://docs.monite.com/docs/currencies#minor-units). For example, $12.50 is represented as 1250.
     *
     * @return self
     */
    public function setSubtotal($subtotal)
    {
        if (is_null($subtotal)) {
            throw new \InvalidArgumentException('non-nullable subtotal cannot be null');
        }
        $this->container['subtotal'] = $subtotal;

        return $this;
    }

    /**
     * Gets tax
     *
     * @return int|null
     */
    public function getTax()
    {
        return $this->container['tax'];
    }

    /**
     * Sets tax
     *
     * @param int|null $tax Registered tax applied for a service price, in [minor units](https://docs.monite.com/docs/currencies#minor-units). For example, $12.50 is represented as 1250.
     *
     * @return self
     */
    public function setTax($tax)
    {
        if (is_null($tax)) {
            throw new \InvalidArgumentException('non-nullable tax cannot be null');
        }
        $this->container['tax'] = $tax;

        return $this;
    }

    /**
     * Gets sender
     *
     * @return string|null
     */
    public function getSender()
    {
        return $this->container['sender'];
    }

    /**
     * Sets sender
     *
     * @param string|null $sender The email address from which the invoice was sent to the entity.
     *
     * @return self
     */
    public function setSender($sender)
    {
        if (is_null($sender)) {
            throw new \InvalidArgumentException('non-nullable sender cannot be null');
        }
        $this->container['sender'] = $sender;

        return $this;
    }

    /**
     * Gets line_items
     *
     * @return \OpenAPI\Client\Model\LineItemDataResponse[]|null
     */
    public function getLineItems()
    {
        return $this->container['line_items'];
    }

    /**
     * Sets line_items
     *
     * @param \OpenAPI\Client\Model\LineItemDataResponse[]|null $line_items The list of items present in the payable.
     *
     * @return self
     */
    public function setLineItems($line_items)
    {
        if (is_null($line_items)) {
            throw new \InvalidArgumentException('non-nullable line_items cannot be null');
        }
        $this->container['line_items'] = $line_items;

        return $this;
    }

    /**
     * Gets ocr_request_id
     *
     * @return string|null
     */
    public function getOcrRequestId()
    {
        return $this->container['ocr_request_id'];
    }

    /**
     * Sets ocr_request_id
     *
     * @param string|null $ocr_request_id Id of OCR request to match asynchronous result of processing payable.
     *
     * @return self
     */
    public function setOcrRequestId($ocr_request_id)
    {
        if (is_null($ocr_request_id)) {
            throw new \InvalidArgumentException('non-nullable ocr_request_id cannot be null');
        }
        $this->container['ocr_request_id'] = $ocr_request_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


