<?php
/**
 * ToDoTasksApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Monite Partner API
 *
 * The Monite REST API, for Monite partners to integrate with our solution.
 *
 * The version of the OpenAPI document: 2023-03-14
 * Contact: developers@monite.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ToDoTasksApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ToDoTasksApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getAllTodoTasksAssignedV1TodoTasksGet
     *
     * Get All Todo Tasks Assigned.
     *
     */
    public function testGetAllTodoTasksAssignedV1TodoTasksGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for howManyTasksDoIHaveV1TodoTasksCountersGet
     *
     * How Many Tasks Do I Have.
     *
     */
    public function testHowManyTasksDoIHaveV1TodoTasksCountersGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readOneTodoTaskV1TodoTasksTodoTaskIdGet
     *
     * Read One Todo Task.
     *
     */
    public function testReadOneTodoTaskV1TodoTasksTodoTaskIdGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateTaskV1TodoTasksTodoTaskIdPatch
     *
     * Update Task.
     *
     */
    public function testUpdateTaskV1TodoTasksTodoTaskIdPatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
