<?php
/**
 * WorkflowsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Monite Partner API
 *
 * The Monite REST API, for Monite partners to integrate with our solution.
 *
 * The version of the OpenAPI document: 2023-03-14
 * Contact: developers@monite.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * WorkflowsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WorkflowsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createNewWorkflowV1WorkflowsPost
     *
     * Create New Workflow.
     *
     */
    public function testCreateNewWorkflowV1WorkflowsPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteWorkflowV1WorkflowsWorkflowIdDelete
     *
     * Delete Workflow.
     *
     */
    public function testDeleteWorkflowV1WorkflowsWorkflowIdDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPipelinesV1WorkflowsPipelinesGet
     *
     * Get Pipelines.
     *
     */
    public function testGetPipelinesV1WorkflowsPipelinesGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getSinglePipelineV1WorkflowsPipelinesPipelineIdGet
     *
     * Get Single Pipeline.
     *
     */
    public function testGetSinglePipelineV1WorkflowsPipelinesPipelineIdGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readPipelinesByWorkflowIdV1WorkflowsWorkflowIdPipelinesGet
     *
     * Read Pipelines By Workflow Id.
     *
     */
    public function testReadPipelinesByWorkflowIdV1WorkflowsWorkflowIdPipelinesGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readSingleWorkflowV1WorkflowsWorkflowIdGet
     *
     * Read Single Workflow.
     *
     */
    public function testReadSingleWorkflowV1WorkflowsWorkflowIdGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for readWorkflowsV1WorkflowsGet
     *
     * Read Workflows.
     *
     */
    public function testReadWorkflowsV1WorkflowsGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
